### PR TITLE
Add some features und fix errors

### PR DESCRIPTION
**Pull request by georf**
I got some broken pipe errors, while trying to create an sublime text plugin to use this gem. I fixed the errors and extend the gem to run with multiple projects at same time.

I hope you understand my goal.

### CODE REVIEW

**Comment by georf** [comment]
@fohte Will you look at the pull request and take over? I would like to use the new features in my projects. But for that I need a Rubygems version.

**Review by fohte — APPROVED** [review]
Thanks @georf, these changes are very useful! LGTM :+1:
I will release the new version soon.

So, I am sorry for the late review.
I didn't have enough time to review and test your contribution because I had been a little busy. :cry:

**Comment by fohte** [comment]
v0.2.0 is released! :tada: ([GitHub](https://github.com/fohte/rubocop-daemon/releases/tag/v0.2.0), [RubyGems.org](https://rubygems.org/gems/rubocop-daemon/versions/0.2.0))

**Comment by georf** [comment]
You're my hero!

Many thanks also for the quick review. You don't need to apologize. It still went much faster than many other projects. I'm sorry if my post caused you stress.

**Pull request merged**
